name: ch2-5-2(手動実行方法)
on:
  workflow_dispatch: # これを指定すると手動実行になる
    inputs:
      greeting: # パラメーター名
        type: string
        default: Hello
        required: true
        description: ほげ
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ inputs.greeting }}"
  
