name: ch3-2-3(デフォルト環境変数)
on:
  workflow_dispatch:
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      # CI = true, GITHUB_ACTION = __run, GITHUB_ACTIONS = true,
      # GITHUB_ACTIONS_PATH = ,
      # GITHUB_API_URL = https://api.github.com,
      # GITHUB_BASE_REF = ,
      # GITHUB_EVENT_NAME = workflow_dispatch,
      # GITHUB_REF_TYPE = branch
      # となった
      - run: >-
          echo CI = ${CI}, GITHUB_ACTION = ${GITHUB_ACTION},
          GITHUB_ACTIONS = ${GITHUB_ACTIONS},
          GITHUB_ACTIONS_PATH = ${GITHUB_ACTIONS_PATH},
          GITHUB_API_URL = ${GITHUB_API_URL},
          GITHUB_BASE_REF = ${GITHUB_BASE_REF},
          GITHUB_EVENT_NAME = ${GITHUB_EVENT_NAME},
          GITHUB_REF_TYPE = ${GITHUB_REF_TYPE},
